services:
  postgres:
    image: postgres:latest
    container_name: ifood_app
    environment:
      - POSTGRES_DB=ifood_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    networks:
      - ifood_app_default

volumes:
  .postgres-data:

networks:
  ifood_app_default:
    external: true
